---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
spec:
  serviceName: valkey-headless
  replicas: 2
  selector:
    matchLabels:
      valkey.sapslaj.cloud/cluster: valkey
  template:
    metadata:
      labels:
        valkey.sapslaj.cloud/cluster: valkey
    spec:
      serviceAccountName: valkey
      containers:
        - name: valkey
          image: valkey/valkey:8
          ports:
            - name: redis
              containerPort: 6379
        - name: valkey-leader
          image: ghcr.io/sapslaj/valkey-leader:latest
          env:
            - name: CLUSTER_NAME
              value: valkey
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: valkey-headless
