name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: go

      - run: go mod download

      - run: go build -v .

      - name: Verify build
        run: ./valkey-leader --help || echo "Binary built successfully"

      - run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch:
          - amd64
          - arm64
        goos:
          - linux
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: go

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: "0"
        run: |
          set -eux
          mkdir -p bin
          go mod download
          go build -v -o "./bin/valkey-leader-$GOOS-$GOARCH" .

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bin/*
          retention-days: 1

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: helm

      - name: Lint Helm chart
        run: helm lint ./helm/valkey-leader

      - name: Template Helm chart (default values)
        run: helm template test-release ./helm/valkey-leader

      - name: Template Helm chart (redis_exporter disabled)
        run: |
          echo "redisExporter:" > /tmp/test-values.yaml
          echo "  enabled: false" >> /tmp/test-values.yaml
          helm template test-release ./helm/valkey-leader -f /tmp/test-values.yaml

      - name: Template Helm chart (ServiceMonitor enabled)
        run: |
          echo "monitoring:" > /tmp/test-values.yaml
          echo "  serviceMonitor:" >> /tmp/test-values.yaml
          echo "    enabled: true" >> /tmp/test-values.yaml
          helm template test-release ./helm/valkey-leader -f /tmp/test-values.yaml

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: buildx, yeet, just

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            # Use short SHA for main branch pushes
            type=raw,value={{sha}},enable={{is_default_branch}}
            # Use git tag for tagged releases
            type=ref,event=tag
            # Use PR number for pull requests
            type=ref,event=pr

      - name: yeet
        run: |
          set -x
          export DOCKER_TAGS='${{ steps.meta.outputs.tags }}'
          export DOCKER_PUSH='${{ github.ref == 'refs/heads/main' }}'
          just docker

  integration-test:
    runs-on: ubuntu-latest
    needs:
      - test-go
      - lint-helm
    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: all

      - name: Create KinD cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: valkey-test

      - name: Wait for cluster to be ready
        run: |
          kubectl cluster-info
          kubectl wait --for=condition=Ready nodes --all --timeout=300s

      - name: Build and load Docker image
        run: just kind-load-image

      - name: Install Helm chart
        run: just helm-test-install

      - name: Test Valkey connectivity and operations
        run: just kind-test-valkey-operations

      - name: Test leader election and failover
        run: just kind-test-failover

      - name: Check logs for any errors
        if: always()
        run: |
          echo "=== Pod Status ==="
          kubectl get pods -l valkey.sapslaj.cloud/cluster=valkey-test

          echo "=== Valkey Leader Logs ==="
          for pod in $(kubectl get pods -l valkey.sapslaj.cloud/cluster=valkey-test -o jsonpath='{.items[*].metadata.name}'); do
            echo "--- Logs for $pod (valkey-leader container) ---"
            kubectl logs $pod -c valkey-leader --tail=50 || true
            echo "--- Logs for $pod (valkey container) ---"
            kubectl logs $pod -c valkey --tail=50 || true
          done

      - name: Test cleanup
        if: always()
        run: just helm-test-uninstall

  build-and-push-helm:
    runs-on: ubuntu-latest
    needs:
      - lint-helm
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: helm

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set chart version for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          sed -i "s/version: .*/version: 0.1.0-${SHORT_SHA}/" ./helm/valkey-leader/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: ${SHORT_SHA}/" ./helm/valkey-leader/Chart.yaml

      - name: Set chart version for tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/version: .*/version: ${TAG_VERSION}/" ./helm/valkey-leader/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: ${TAG_VERSION}/" ./helm/valkey-leader/Chart.yaml

      - name: Package Helm chart
        run: |
          helm package ./helm/valkey-leader --destination ./helm-packages

      - name: Push Helm chart to GHCR
        run: |
          CHART_VERSION=$(helm show chart ./helm/valkey-leader | grep '^version:' | awk '{print $2}')

          # Push with version tag
          helm push ./helm-packages/valkey-leader-${CHART_VERSION}.tgz oci://ghcr.io/sapslaj/valkey-leader-chart

      - name: Generate chart metadata
        run: |
          CHART_VERSION=$(helm show chart ./helm/valkey-leader | grep '^version:' | awk '{print $2}' | head -1)
          echo "Chart version: $CHART_VERSION"
          echo "Registry: oci://ghcr.io/sapslaj/valkey-leader-chart"
          echo "Installation command:"
          echo "  helm install my-valkey oci://ghcr.io/sapslaj/valkey-leader-chart --version $CHART_VERSION"

  yoke-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: go,just

      - run: just yoke

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: yoke
          path: ./bin/*
          retention-days: 1
